
#ifndef EXAMPLE_EXECUTABLE_API_H
#define EXAMPLE_EXECUTABLE_API_H

#ifdef EXAMPLEEXECUTABLE_STATIC_DEFINE
#  define EXAMPLE_EXECUTABLE_API
#  define EXAMPLEEXECUTABLE_NO_EXPORT
#else
#  ifndef EXAMPLE_EXECUTABLE_API
#    ifdef ExampleExecutable_EXPORTS
        /* We are building this library */
#      define EXAMPLE_EXECUTABLE_API 
#    else
        /* We are using this library */
#      define EXAMPLE_EXECUTABLE_API 
#    endif
#  endif

#  ifndef EXAMPLEEXECUTABLE_NO_EXPORT
#    define EXAMPLEEXECUTABLE_NO_EXPORT 
#  endif
#endif

#ifndef EXAMPLEEXECUTABLE_DEPRECATED
#  define EXAMPLEEXECUTABLE_DEPRECATED __declspec(deprecated)
#endif

#ifndef EXAMPLEEXECUTABLE_DEPRECATED_EXPORT
#  define EXAMPLEEXECUTABLE_DEPRECATED_EXPORT EXAMPLE_EXECUTABLE_API EXAMPLEEXECUTABLE_DEPRECATED
#endif

#ifndef EXAMPLEEXECUTABLE_DEPRECATED_NO_EXPORT
#  define EXAMPLEEXECUTABLE_DEPRECATED_NO_EXPORT EXAMPLEEXECUTABLE_NO_EXPORT EXAMPLEEXECUTABLE_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef EXAMPLEEXECUTABLE_NO_DEPRECATED
#    define EXAMPLEEXECUTABLE_NO_DEPRECATED
#  endif
#endif

#endif /* EXAMPLE_EXECUTABLE_API_H */
